[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "supabase-mcp-server"
version = "3.1.0"
description = "Supabase MCP Server (FastMCP + Smithery)"
authors = [
    {name = "coupaul", email = "contact@coupaul.fr"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.7.0",
    "mcp>=0.4.0",
    "smithery>=0.1.23"
]

[tool.smithery]
server = "supabase_mcp_server.server:create_server"