[project]
name = "supabase-mcp-oauth2"
version = "3.1.0"
description = "Enhanced Edition v3.1 - 54+ MCP tools for 100% autonomous Supabase management with OAuth2 support, advanced DDL operations, and comprehensive database automation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.13.0",
    "smithery>=0.1.23",
    "pydantic>=2.0.0",
]

# Points to your server function
[tool.smithery] 
server = "src.supabase_server:create_server"
