[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PORT = "8002"
NODE_ENV = "production"
MINECRAFT_VERSION = "1.6.4"
FORGE_VERSION = "1.6.4-9.11.1.965"