[build]
builder = "dockerfile"

[deploy]
startCommand = "python src/supabase_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
PORT = "8000"
PYTHONUNBUFFERED = "1"