#!/bin/bash

# Script de déploiement sur mcp.coupaul.fr
# Ce script vous guide pour déployer votre serveur MCP sur votre domaine

echo "🚀 Guide de déploiement sur mcp.coupaul.fr"
echo ""

echo "📋 Options de déploiement disponibles:"
echo ""
echo "1. 🌐 Smithery (Recommandé - Déjà fait)"
echo "   ✅ Déploiement automatique"
echo "   ✅ Gestion des sessions"
echo "   ✅ Interface web intégrée"
echo "   ✅ Pas de configuration serveur"
echo ""
echo "2. 🐳 Docker sur votre serveur"
echo "   - Déployez le Dockerfile sur votre serveur"
echo "   - Configurez le reverse proxy (nginx/apache)"
echo "   - Pointez mcp.coupaul.fr vers votre serveur"
echo ""
echo "3. ☁️ VPS/Cloud (Railway, Render, etc.)"
echo "   - Déployez directement depuis GitHub"
echo "   - Configurez le domaine personnalisé"
echo "   - Gestion automatique des déploiements"
echo ""
echo "4. 🏠 Serveur dédié"
echo "   - Installez Python et les dépendances"
echo "   - Configurez le serveur web"
echo "   - Déployez manuellement"
echo ""

echo "🔧 Configuration nécessaire pour mcp.coupaul.fr:"
echo ""
echo "1. 📁 Fichiers de configuration:"
echo "   - Dockerfile (déjà présent)"
echo "   - pyproject.toml (déjà configuré)"
echo "   - src/supabase_server.py (serveur MCP)"
echo ""
echo "2. 🌐 Configuration DNS:"
echo "   - CNAME: mcp.coupaul.fr → votre-serveur.com"
echo "   - Ou A record vers l'IP de votre serveur"
echo ""
echo "3. 🔒 Configuration SSL:"
echo "   - Certificat SSL pour HTTPS"
echo "   - Configuration reverse proxy"
echo ""

echo "💡 Recommandation:"
echo "   Utilisez Smithery pour le développement et les tests"
echo "   Déployez sur mcp.coupaul.fr pour la production"
echo ""

echo "🎯 Prochaines étapes:"
echo "1. Testez votre serveur sur Smithery"
echo "2. Configurez vos clés Supabase"
echo "3. Testez les outils MCP"
echo "4. Déployez sur mcp.coupaul.fr si nécessaire"
echo ""

echo "✅ Guide terminé !"
