#!/bin/bash
# Script de configuration Railway pour mcp.coupaul.fr

echo "🚂 Configuration Railway pour mcp.coupaul.fr"
echo "============================================"
echo ""

echo "📋 Variables d'environnement à configurer dans Railway Dashboard:"
echo "================================================================="
echo ""
echo "1. PORT=8000"
echo "2. PYTHONUNBUFFERED=1"
echo "3. SUPABASE_URL=https://votre-projet.supabase.co"
echo "4. SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "5. SUPABASE_SERVICE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... (optionnel)"
echo ""

echo "🔧 Instructions Railway Dashboard:"
echo "=================================="
echo ""
echo "1. 🌐 Allez sur Railway Dashboard:"
echo "   https://railway.app"
echo ""
echo "2. 📁 Sélectionnez votre projet MCP"
echo ""
echo "3. ⚙️ Allez dans Settings > Variables"
echo ""
echo "4. ➕ Ajoutez chaque variable:"
echo "   - Cliquez sur 'Add Variable'"
echo "   - Nom: PORT, Valeur: 8000"
echo "   - Nom: PYTHONUNBUFFERED, Valeur: 1"
echo "   - Nom: SUPABASE_URL, Valeur: [votre URL Supabase]"
echo "   - Nom: SUPABASE_ANON_KEY, Valeur: [votre clé anonyme]"
echo ""
echo "5. 🚀 Vérifiez la configuration du service:"
echo "   - Settings > Service"
echo "   - Start Command: laissez vide (utilise le CMD du Dockerfile)"
echo "   - Ou définissez: python ultra_simple_server.py"
echo ""

echo "🔍 Vérification du Dockerfile:"
echo "=============================="
echo "Le Dockerfile devrait contenir:"
echo "FROM python:3.12-slim"
echo "WORKDIR /app"
echo "COPY ultra_simple_server.py ."
echo "EXPOSE 8000"
echo "CMD [\"python\", \"ultra_simple_server.py\"]"
echo ""

echo "🧪 Test après configuration:"
echo "============================"
echo "1. Déployez avec: railway up --detach"
echo "2. Vérifiez les logs: railway logs"
echo "3. Testez l'endpoint: curl https://mcp.coupaul.fr/health"
echo ""

echo "❌ Problème actuel:"
echo "==================="
echo "Railway essaie d'exécuter 'src/supabase_server.py' au lieu de 'ultra_simple_server.py'"
echo "Cela indique que:"
echo "- Le Start Command Railway est mal configuré"
echo "- Ou Railway utilise une ancienne configuration"
echo ""

echo "✅ Solution:"
echo "============"
echo "1. Videz le Start Command dans Railway Dashboard"
echo "2. Ou définissez: python ultra_simple_server.py"
echo "3. Redéployez le service"
echo ""

echo "🎯 Une fois configuré, Railway devrait:"
echo "======================================"
echo "✅ Démarrer ultra_simple_server.py"
echo "✅ Exposer le port 8000"
echo "✅ Répondre à /health"
echo "✅ Passer le healthcheck Railway"
echo ""

echo "📞 Support Railway:"
echo "=================="
echo "Si le problème persiste:"
echo "1. Vérifiez les logs Railway Dashboard"
echo "2. Redémarrez le service"
echo "3. Contactez le support Railway"
